[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/lambdaServer/*"
  status = 200
  to = "/.netlify/functions/lambdaServer/:splat"
